{% set version = "2.1-4" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-gstat
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/gstat_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gstat/gstat_{{ version }}.tar.gz
  sha256: fafcbd6c480f4e996a904f54b8efa64af2fad8fef2ec0f706e058ada4618c630

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  skip: true  # [ppc64le]

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib('m2w64_c') }}    # [win]
    - {{ posix }}filesystem      # [win]
    - {{ posix }}make
    - {{ posix }}sed             # [win]
    - {{ posix }}coreutils       # [win]
    - {{ posix }}zip             # [win]
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-fnn                      # [build_platform != target_platform]
    - r-lattice                  # [build_platform != target_platform]
    - r-sf >=0.7_2               # [build_platform != target_platform]
    - r-sftime                   # [build_platform != target_platform]
    - r-sp >=0.9_72              # [build_platform != target_platform]
    - r-spacetime >=1.2_8        # [build_platform != target_platform]
    - r-stars                    # [build_platform != target_platform]
    - r-zoo                      # [build_platform != target_platform]
  host:
    - r-base
    - r-fnn
    - r-lattice
    - r-sf >=0.7_2
    - r-sftime
    - r-sp >=0.9_72
    - r-spacetime >=1.2_8
    - r-stars
    - r-zoo
  run:
    - r-base
    - r-fnn
    - r-lattice
    - r-sf >=0.7_2
    - r-sftime
    - r-sp >=0.9_72
    - r-spacetime >=1.2_8
    - r-stars
    - r-zoo

test:
  commands:
    - $R -e "library('gstat')"           # [not win]
    - "\"%R%\" -e \"library('gstat')\""  # [win]

about:
  home: https://github.com/r-spatial/gstat/
  license: GPL-2.0-or-later
  summary: Variogram modelling; simple, ordinary and universal point or block (co)kriging; spatio-temporal kriging; sequential Gaussian or indicator (co)simulation; variogram and variogram map plotting utility functions; supports sf and stars.
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - jsignell
