{% set version = '1.1-6' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gstat
  version: {{ version|replace("-", "_") }}

source:
  fn: gstat_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/gstat_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gstat/gstat_{{ version }}.tar.gz
  sha256: 4618a941a62421f31104421c9ca5a1ea4ec17c283027908244edb5e8d2e47ba5

build:
  merge_build_host: True  # [win]
  number: 1000
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-fnn
    - r-lattice
    - r-sp >=0.9_72
    - r-spacetime >=1.0_0
    - r-zoo
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-fnn
    - r-lattice
    - r-sp >=0.9_72
    - r-spacetime >=1.0_0
    - r-zoo

test:
  commands:
    - $R -e "library('gstat')"           # [not win]
    - "\"%R%\" -e \"library('gstat')\""  # [win]
    - conda inspect linkages -p $PREFIX r-gstat  # [not win]
    - conda inspect objects -p $PREFIX r-gstat  # [osx]

about:
  home: https://github.com/edzer/gstat/
  license: GPL (>= 2.0)
  summary: Variogram modelling; simple, ordinary and universal point or block (co)kriging; spatio-temporal
    kriging; sequential Gaussian or indicator (co)simulation; variogram and variogram
    map plotting utility functions.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - jsignell
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
