travis:
  secure:
    BINSTAR_TOKEN: MnuN5VKlteq5J1PUWyFWy1RnXEH+EJHrhF7P6pIu8zOS9qeO+gohX4a5a3Ye6eDVxyTFBxaDN6FFEuDFHh0L5NaGka9wVyvhENFsfLxVMwdROMLE4+tqfMXELdqx3zPQ32Wse5j6Huz+Fw1d4YHbeUYJEpwczBHakATEzrbhsW/xYF6fPBdLFmyZbd96yJvtmYUVMTSiwGk7BaA+ASxz1UYRDd1eIXu/guXw3O15mNEHJlzSkShmSNNUI7wsFkGyaoYt2SvVajQEiL2zHlkA35YhLbo9yTloGOuJdaviwo3tvFM45UTZUivGqOeQubdS/wVoHB18TVoVqi21uO8d0DtkHWH3sGiYTWEpQrp2QMBkLWZUyA0Qa00qzB2vgd/TtJ04Alcro0oAgEJ2e3A5II38J1vs/a2I7fvlsMrFbmNc236FIUJZIe6h+IVpz7vTfXan8JwKUQFJ50EpMC/9SOXTsSzs/QTROse7ojlZKobLdFpqbIciNDzqR/bqNpCgT8qnbSPv0RhWu0VwZtSK2GcbrHvJrCpH1RMBLebFrRckWCrTJvn/RTllLvaudYMFNr8qz/u4D6WGs/X7qXbhlAVutJdgwI0hMtX85UTUYFyLfmlkiMD/NVz/6po/17drX6i+humAuBb6oWvtaMeiUarkQ+1qQX61BDKRulTdHlU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
