travis:
  secure:
    BINSTAR_TOKEN: Uavp/T/3bgDaniuy+NEBHkFsk32PN/h/rzNZ603cU7Go2R9YXMaji42Dv62Njf21MoS69d+Jy5TLZvt/uXZ3FwdFFO4MGxdNW13zZAy6Zu3Z9GIT7sBSXPOUrfVYcAaeTnpfpi6FNL1OUFuomMBjLQT35ymMBTVWgu9kXFJtQbWOKDd25ABejcbwZGOcAa7UknJ8LPso+/nlC9wfP4gvOFOYuDl0EXZ5/P8lZ4Vv5X89bpGbFLsbnkKCE8so/Mu3ZR0TWftrcTCP7iJWC6G8c5H/Z3pgu8Pyf70gNy4bH3M7ElSoJJOCJ6MZ8lsbPN5U32PjuWPUT35EiZEpH+yBK8gQneFT0odZTlnRh+bHFjQQflnJrL0rFvFI3jt6Y65rzva6l4Bvq+csOT0q9LAeI7NxOCuduarAKeKD0uBMWYwxMs/xurKS8dMvl9RZov72r3Rj+yaKc5qlEtKAafQMBUpbclW+g2MWzTwCzgQUeduUhxlvZxa+x7T+WI40n+iQDxdCKNhR8KyOdMKtybZAfwZi2URa5ORl91h9DnRdCK5I3dUe5FJVGBZzS/Gju+plzFGyWio9zO+JgvNnn10bmICiw6lWBqQY/1fUm6/GNA5KWaKE2BaQOyoN8DQp8V7ZmLzvjlR+4EI2foMb2iEg0ypeIrxIiNZN1IaPJtzegf8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
