travis:
  secure:
    BINSTAR_TOKEN: chj0RxopkeOAdolK7U1CNINK6K04A8eUaDPAhATWV8BRKLuU6YRonpnpqfJA4rQlYMkGmcfwndMmm+J9kwvKkG4yDWPXAKrhuT0DnMZRhpYmX3sxcVf66scPfQsEd4VpGPfzV1w+NQ6pvudxXKESV3x1ikWlw4kcOgli6HN8yk+jd5cKPcXbbYyRWeH5VDn1w4Sqg9SjGr0ZM/ds4Xc6t5OMmqJ/rSbK3g/Q+1+oJU/ySnrP/Qee6VawLJXfLRrGVsfsYOxgrpvmXxY/UlBlOm/wBiLakAwDPcpS1LXwCj+rMYhf+/cSCNiKn5VbJ8E7KZvpVegML/ihvPBc+fPHUcECPcmIqPHkZm12JHZ7OhDJt5HoNG3CJvc6lmdJ9aADgOZJ/A+pASj/phepUGQgRiwDmnZIQOz4cXg29YcgFsnYwXoPfsU3fsD7jnjygzYcTXS+Qqh+4NCXJtQFW5foJUX6tCBEwXWNDv3XCmON5HlG4AaiELivIo8pmzJ2bXBd9PTtKvk+uRlFA8SbMc/KdcOsqA3muOLti0sWA19Qzq6bjUYU8BeAnx0LDmKIdQ/TZkzw0UGHgoZKu2n9OrBmfiKsOYE2NoaE4j3+GAmY+1aPviDIEM5YGfH+Eix/tRHbp8/YDocWCGeWyoiJOhJ/vwjKZh7/OCM5nw+NUZopUc8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
