travis:
  secure:
    BINSTAR_TOKEN: bhaIUdTM03lBosUcCOLL4cRpeXnLA8zBF0tZOXU5Wuw9DBDpWfwKCQk6DOC+nNuRVk9Ff7CrRDb5j2g1nFxwKXEAvN7qBXk/IxWdl9IGvXOsjmFJLvz2leiHP1iWW416UmmeAjwvaSbnWpq5kv3s0eLdZowxGw2mSSqYgwRzYHSsnIENm0BT2xqkHlbjiXbwhmOMDfIDRY3aovRW+b94i9q6wakhcn2mBapfjVy0XYMsDFY+SoTpUzYwkWDXv3xA/zAVRW/KIFS+uT/Nk1XFrh2OgdwSXRegpwE4DihSDEQEtqy93uXLi+Egb9zE5+f5p7XsrfRJP1pjj+85FFcVOYLnvXDwiE8o71c3ieyiJ551NH4c87VA41zQ16jNNV/XWznSwYCqOvNW/vm5bt8RykU4kbr+b0MVP9t/GbUDfV6SDSFBH3MUqQtbglAeqTkqyyqFei2M5yvEfFMw+5/VuvA4yf8tdPea9TXIQQwFDqQlNowmLvqHc5Jh1e2+KWcNacK4EKDd0lTrLiUivH1e/x2bQ1jKCx3wdgEFWd63G3FwS+FkI+WHiT6sGCC7ceQpfX+DoNUYIdvYi+wekhM6/6I+OH2BQuJzV8H8Kf5h56y30liBcTFvOGHkRWMypE9RHX2wwxxNJq6a2NeWLeQF5PTjKiCG7VfPdsPtOcISJEU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
