appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: nzkr7MDyeLUSEMhjgca63kYxYplSPXQpQEmNVvuVTO40LjlY+kvKt0YemQkGRdn9zy1fTdE2vboPlWIZzJT14DcTKW4yQ0DRx/D4gZW02czoIpAph/c6czzxSVhOb8GcBcbTByRqwjzLU50t930nCqt0aNDBJF+Bc0nsAy1wPxdx6rmjlxRaypOUFKej7Qrh5CHr/aWY+Wkgx84EI6UB7mMgLBSAJkqVa+5esIJ9JD8fyewwiCEoj0M5yyBztHq7R3jNz13r/0nH15cyBztIVMyJThR/98NXfAUyuiIbbAANcCaAAQONDdDCLMfeO3k91GKFgz8XPSd0dhAO1l24hnRAgu5YNW2qqc3ZxtfnxZTGw/Y18Y+Fy5TgTwHhFS3ILk2C9E1zfx3QXSAQqrgAKGqFAFWpGV81lyVA05sAmRPVvkn5/vMSX5uTZf93G+nMzLCtRmiGS3RtU7Pci68sfNRnZrYNSK5/8TlCWfINDIZ3hhYKf5uJII95tJkq7K11U8aY78wAR06MxbG6SKRdCWe3kcA4x5dr2AFl2va++Bt+4iKDDStvkCJDN+SgAOWYo2Q0LVNsacHJ7FSSrfUhGJRYCZ8mZZul4HskIRvH2EGAttj5/ZEc/Ajx/FfZ73yjY00vI95jwu7QGRIAweTq2Xk/5ZqgqfDmrQumj/IwNMM=}
bot:
  automerge: true
